name: flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  water_drop_nav_bar: ^2.2.0+5  # Remplacez 'latest_version' par la version souhaitée
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter: 
    sdk: flutter
  auth_buttons: ^3.0.0
  #google_fonts: ^3.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
assets:
  - assets/images/ 
