name: flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get: 4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Oswald
      fonts:
        - asset: assets\fonts\Oswald-VariableFont_wght.ttf
    - family: Raleway
      fonts:
        - asset: assets\fonts\Raleway-Italic.ttf
        - asset: assets\fonts\Raleway-Regular.ttf
          style: italic
    - family: Courgette
      fonts:
        - asset: assets\fonts\Courgette-Regular.ttf

  uses-material-design: true
